scripts/README.adoc
scripts/local/init/env.properties

Updated local env to pull the latest BUILD-SNAPSHOT.

A small README polish.

---

cloudfoundry/server/create.sh

cleaning manifest file

---

cloudfoundry/binder/rabbit/create.sh
cloudfoundry/binder/rabbit/env.properties
kubernetes/binder/kafka/create.sh
kubernetes/binder/kafka/env.properties
kubernetes/binder/rabbit/create.sh
kubernetes/binder/rabbit/env.properties
local/binder/kafka/create.sh
local/binder/kafka/env.properties
local/binder/rabbit/create.sh
local/binder/rabbit/env.properties

Adding registration resource back

---

local/common.sh

Removing container data

---

run.sh

Removing local caching of server jar

---

README.adoc
cloudfoundry/binder/rabbit/config.sh
cloudfoundry/binder/rabbit/create.sh
cloudfoundry/server/config.sh
cloudfoundry/server/create.sh
kubernetes/binder/kafka/config.sh
kubernetes/binder/kafka/create.sh
kubernetes/binder/kafka/destroy.sh
kubernetes/binder/rabbit/config.sh
kubernetes/binder/rabbit/create.sh
kubernetes/binder/rabbit/destroy.sh
kubernetes/init/setenv.sh
kubernetes/mysql/create.sh
kubernetes/mysql/destroy.sh
kubernetes/mysql/mysql.yml
kubernetes/redis/create.sh
kubernetes/redis/destroy.sh
kubernetes/server/config.sh
kubernetes/server/create.sh
kubernetes/server/destroy.sh
local/binder/kafka/config.sh
local/binder/kafka/create.sh
local/binder/rabbit/config.sh
local/binder/rabbit/create.sh
local/server/config.sh
local/server/create.sh
run.sh

- we should still see the environment set properly for the server and binder settings
Resolves #96 
Resolves #95

Adding config scripts so we can run automated with `-s` flag

---

kubernetes/server/create.sh
kubernetes/server/scdf.yml
kubernetes/server/secret.yml

- add a 5 s sleep before starting server to wait for secret and configMap creation
Resolves #104

Make k8s SCDF server startup more resilient

---

local/init/env.properties
run.sh

Update version for local and add about logging

---

src/main/java/org/springframework/cloud/dataflow/acceptance/test/util/StreamDefinition.java
src/test/java/org/springframework/cloud/dataflow/acceptance/test/NamedChannelTests.java

- fixed StreamDefinition DSL to ensure only applicable operations are made available
- added javadoc

GH-112 Fixed DSL for consistency

---

kubernetes/server/config.sh
kubernetes/server/create.sh

Fixing column to fetch IP from

---

run.sh

Call delete-orphaned-routes only if platform is CF

---

kubernetes/init/setenv.sh
kubernetes/skipper-server/config.sh
run.sh

Remove defaulting of DF and Skipper versions

---

README.adoc
kubernetes/scheduler/create.sh
kubernetes/scheduler/destroy.sh
src/test/java/org/springframework/cloud/dataflow/acceptance/test/AbstractTaskTests.java

ATs for scheduling on K8s

---

src/test/java/org/springframework/cloud/dataflow/acceptance/test/AbstractStreamTests.java
src/test/java/org/springframework/cloud/dataflow/acceptance/test/TickTockTests.java

- Add update/rollback operation methods in `AbstractStreamTests`
- Add a test case that verifies update/rollback
Resolves #152

Add Stream update/rollback tests

---

acceptance-tests/build.gradle
acceptance-tests/custom-apps/dataflow-server-with-drivers-template1/build.gradle
acceptance-tests/custom-apps/dataflow-server-with-drivers-template2/build.gradle
acceptance-tests/custom-apps/skipper-server-with-drivers-template1/build.gradle
acceptance-tests/custom-apps/skipper-server-with-drivers-template2/build.gradle
acceptance-tests/custom-apps/skipper-server-with-drivers-template3/build.gradle
acceptance-tests/docker-images/oracle/dockerfiles/12.1.0.2/installPerl.sh
mvnw
mvnw.cmd
pom.xml

This commit updates URLs to prefer the https protocol. Redirects are not followed to avoid accidentally expanding intentionally shortened URLs (i.e. if using a URL shortener).
These URLs were switched to an https URL with a 2xx status. While the status was successful, your review is still recommended.
* http://www.apache.org/licenses/LICENSE-2.0 migrated to:  
https://www.apache.org/licenses/LICENSE-2.0 ([https](https://www.apache.org/licenses/LICENSE-2.0) result 200).
* http://www.cpan.org/src/5.0/perl-5.14.1.tar.gz migrated to:  
https://www.cpan.org/src/5.0/perl-5.14.1.tar.gz ([https](https://www.cpan.org/src/5.0/perl-5.14.1.tar.gz) result 200).
* http://repo.springsource.org/ext-private-local migrated to:  
https://repo.springsource.org/ext-private-local …

URL Cleanup

---

acceptance-tests/spring-cloud-dataflow-acceptance-tests/src/test/java/org/springframework/cloud/dataflow/acceptance/tests/AbstractDataflowTests.java
cloudfoundry/binder/rabbit/config.sh
cloudfoundry/binder/rabbit/env.properties
kubernetes-common/binder/kafka/config.sh
kubernetes-common/binder/kafka/env.properties
kubernetes-common/binder/rabbit/create.sh
kubernetes-common/binder/rabbit/env.properties
local/binder/kafka/config.sh
local/binder/kafka/env.properties
local/binder/rabbit/config.sh
local/binder/rabbit/env.properties
run.sh

- dataflow.spring.io redirects
- Remove unused app registration usages
- update for local, CF and K8s environment properties for Kafka/RabbitMQ binders
Resolves #205

Update app import URIs to use the latest

---

src/test/java/org/springframework/cloud/dataflow/acceptance/test/SchedulerTests.java

Do not merge until https://github.com/spring-cloud/spring-cloud-dataflow/issues/3843 has been merged

Updated the tests so that the suffix for schedule names has been removed

---

README.adoc
src/main/java/org/springframework/cloud/dataflow/acceptance/test/util/DataFlowTemplateBuilder.java
src/main/java/org/springframework/cloud/dataflow/acceptance/test/util/HttpPoster.java
src/main/java/org/springframework/cloud/dataflow/acceptance/test/util/RestTemplateConfigurer.java
src/main/java/org/springframework/cloud/dataflow/acceptance/test/util/TestConfigurationProperties.java
src/test/java/org/springframework/cloud/dataflow/acceptance/test/AbstractStreamTests.java
src/test/java/org/springframework/cloud/dataflow/acceptance/test/AbstractTaskTests.java
src/test/java/org/springframework/cloud/dataflow/acceptance/test/util/SchedulerRule.java

Add support to use HTTPS to post to the http source in tests

Support for https posts

---

batch-remote-partition/pom.xml
src/test/java/org/springframework/cloud/dataflow/acceptance/test/BatchRemotePartitionTests.java

- update boot version
- need to build and push `springcloud/batch-remote-partition:0.0.2-SNAPSHOT` image before merging

Add postgresql jdbc driver for batch-remote-partition

---

scripts/tests.sh
src/test/java/org/springframework/cloud/dataflow/acceptance/test/BatchRemotePartitioningAT.java
src/test/java/org/springframework/cloud/dataflow/acceptance/test/TaskScheduleAT.java

Depends on https://github.com/spring-cloud/spring-cloud-dataflow/pull/4435

Delegate dataflowTemplate build to rest-client

---

kubernetes/apps/register-apps.sh
kubernetes/init/tmc-create.sh
kubernetes/init/tmc-delete.sh
kubernetes/server/server-uri.sh
kubernetes/skipper-server/create.sh
kubernetes/skipper-server/scdf-https-distro-patch.json
kubernetes/skipper-server/scdf-https-helm-patch.json
kubernetes/skipper-server/scdf-svc-distro-patch.yaml
kubernetes/skipper-server/scdf-svc-helm-patch.yaml
kubernetes/skipper-server/server-uri.sh
kubernetes/skipper-server/skipper-https-distro-patch.json
kubernetes/skipper-server/skipper-https-helm-patch.json
kubernetes/skipper-server/skipper-svc-distro-patch.yaml
kubernetes/skipper-server/skipper-svc-helm-patch.yaml
scripts/setup.sh
scripts/tests.adoc
scripts/tests.sh

Depends on https://github.com/spring-cloud/spring-cloud-deployer-kubernetes/pull/432

Enable HTTPS + TMC installation

---

performance-tests/task-perf-tests-initializer/README.adoc
performance-tests/task-perf-tests-initializer/src/main/java/org/springframework/cloud/dataflow/perf/test/task/configuration/TaskPerformanceConfiguration.java
performance-tests/task-perf-tests-initializer/src/main/java/org/springframework/cloud/dataflow/perf/test/task/configuration/TaskPerformanceProperties.java
performance-tests/task-perf-tests-initializer/src/main/java/org/springframework/cloud/dataflow/perf/test/task/configuration/TaskUtils.java

Added ability to create job instances for a task execution

---

scripts/at-test-script.sh

fix script exit status

---

acceptance-tests/ci/scripts/build-timestamp-batch-with-drivers.sh
acceptance-tests/custom-apps/timestamp-batch-with-drivers-template1/build.gradle
acceptance-tests/custom-apps/timestamp-batch-with-drivers-template1/gradle/wrapper/gradle-wrapper.properties
scripts/at-test-script.sh

Invoke build-timestamp-batch-with-drivers.sh before tests.

Ensure using the jdbc drivers from Maven Central.

---

.github/workflows/at-common-workflow.yml
acceptance-tests/ci/scripts/build-timestamp-batch-with-drivers.sh
acceptance-tests/custom-apps/timestamp-batch-with-drivers-template1/build.gradle
scripts/at-test-script.sh

Ensure maven local is in default location

Ensure maven local is in default location

---

.github/workflows/acceptance-tests-for-kafka-0.yml
.github/workflows/acceptance-tests-for-kafka-1.yml
.github/workflows/acceptance-tests-for-kafka-2.yml
.github/workflows/acceptance-tests-for-rabbit-0.yml
.github/workflows/acceptance-tests-for-rabbit-1.yml
.github/workflows/acceptance-tests-for-rabbit-2.yml
.github/workflows/scheduled-acceptance-tests.yml

Remove schedules and use only one Scheduled job.

Use needs to ensure jobs for specific environments run separately.

---

.github/workflows/acceptance-tests-for-kafka-0.yml
.github/workflows/acceptance-tests-for-kafka-1.yml
.github/workflows/acceptance-tests-for-rabbit-0-oracle.yml
.github/workflows/acceptance-tests-for-rabbit-0.yml
.github/workflows/acceptance-tests-for-rabbit-1.yml
.github/workflows/at-common-workflow.yml
.github/workflows/scheduled-acceptance-tests.yml

Update CF envs

---

scripts/at-test-script.sh

Fixes https://github.com/spring-cloud/stream-applications/issues/277

Register specific version of stream apps.

---

pom.xml
src/local/local-k8s-test.sh
src/test/java/org/springframework/cloud/dataflow/acceptance/test/DataFlowAT.java

Catch failures of HTTP Post in older versions.
Provide for test groups

Improved local scripts.

---

pom.xml
src/test/java/org/springframework/cloud/dataflow/acceptance/test/DataFlowAT.java
src/test/java/org/springframework/cloud/dataflow/acceptance/test/TaskScheduleAT.java

* Also simplified version check for Boot3 jobs

Updated Dataflow versions to latest snapshot

---

src/test/java/org/springframework/cloud/dataflow/acceptance/test/DataFlowAT.java

* Update versions of apps to recent 3.2.1

[2.11.1 ATs] DataFlowAT.applicationMetadataDockerTests

---

.github/workflows/run-scdf-at.yml

- **Optionally upload the Stemcell when running a single AT**
- **Trim whitespace**

Upload Stemcell

---

.github/workflows/run-scdf-at.yml

Always clean up leases unless requested

---

.github/workflows/run-scdf-at.yml

Fix github status check

---

.github/workflows/run-scdf-at.yml

Fix checkout action for cleanup

---

.github/workflows/run-scdf-at.yml

Decouple lease creation from installation

---

.github/workflows/run-scdf-at.yml

Fix cleanup condition to work with boolean types

---

.github/workflows/run-scdf-at.yml

- **Rename input to stemcell-version for consistency**
- **Simplify lease clean-up condition**

Simplify lease clean-up condition
